language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master

addons:
  ssh_known_hosts:
    - sdweb.ece.iastate.edu

script:
  - npm install -g bower
  - bower install
  - ./tools/build.sh

